name: Hoge
on:
  workflow_dispatch:

jobs:
  setdirs:
    uses: ./.github/workflows/set-dirs.yml
  fuga:
    name: Fuga
    needs: setdirs
    if: needs.setdirs.outputs.has_dirs == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        dir: ${{fromJson(needs.setdirs.outputs.dirs)}}
    steps:
      - name: Run
        run: |
          echo ${{ matrix.dir }}
